# Generated by Django 3.2.25 on 2024-10-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talriz_app', '0002_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='talriz_app.Category'),
        ),
    ]
