# Generated by Django 3.2.25 on 2024-10-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talriz_app', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(choices=[('general', 'General')], related_name='items', to='talriz_app.Category'),
        ),
    ]
