# Generated by Django 3.2.25 on 2024-10-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talriz_app', '0005_alter_item_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
    ]
